before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: xB6HHdmNkrsfted7AT76GJjx/SKmwL0zgcjzksZyLuoXTo+fC97xtW2FI8YuW+ef0/VHf/G949z9T1eHGQy/NT6wzgDuKieuBEL05ae0aKPtu2r+dlqTG1pJSFTRj95ksolTaVastckzE5KmEQIJ0da6H4FuUt6vhCCoNEVlnMsJSeIlaAAiWhZchInqPKcUbYp3X3Aa/JTLXnhOlMOxYOlif/KFd4pIzrmbM3kBE0Ok9/8xk6V22BCglMmQGJ5Df+5m7tgUmyQs/GK5RqA1iyU5H4P9Tgbz3tuQ3GvNQ+BiXP+zEli9DvQUaDyYk4K0BcmwmruTpdWuy6O41ie6yVXAQppjQY4qhl7LMLeiRDB+137kfi7Pqs8YE1N+9fXNl9OJ5B6ngX3auBT7FiNnjuT/xpx1WB98N7er6CVpXRRsIlJ4+TwNmBKqty9Tq0qnZc1XeDPk6LYWhLT4/vevHnKHw/rQMAOWGxbZlrQzOuTgRBq+bbDbKvJARvQA1EqAY+ulyTKKNEgMHiI04iFKSBnJwOPXU00U4D4KbFRbqsd2JVFTqGUzBAFtRJbqjVlyw5G8lB3d2l+YbhQybjUo1TRyOhPDwr3fgfc3/puvDpxDiCJMkHqdZJyzjYh5oWMwlRYIPerj3I8JI1BcRjPOS2OwhtoxvhaNZ5beNz864DU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
